#!/bin/bash

# ==========================================
# HACKERS_SHELL_GPT (sgpt) AI Configuration Script
# Target Environment: Kali Linux / Debian
# ==========================================

# --- ANSI Color Codes for UI ---
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
PURPLE='\033[0;35m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# --- Global Configurations ---
CONFIG_DIR="$HOME/.config/shell_gpt"
CONFIG_FILE="$CONFIG_DIR/.sgptrc"
SHELL_RC_FILE="$HOME/.$(basename "$SHELL")rc"
ACTIVATION_KEY=""
DEFAULT_MODEL="azure/gpt-4o"
USE_LITELLM="true"
API_BASE_URL="https://apiservice5lh2czy2mmcta.azure-api.net/ecc-sqmp-v1/"
AZURE_API_VERSION="2024-09-01-preview"

# --- 1. Elegant Figlet/ASCII Banner with Logo ---
print_banner() {
    clear
    # Cyber-Skull Logo in Red
    echo -e "${RED}${BOLD}"
    cat << "EOF"
      .---.
     /     \   [ SYSTEM UPLINK INITIATED ]
    | () () |
     \  ^  /
      |||||    [ ESTABLISHING SECURE CONNECTION ]
      '---'
EOF

    # Main HACKERS_SHELL_GPT Banner in Cyan
    echo -e "${CYAN}${BOLD}"
    cat << "EOF"
 _   _    _    ____  _  _______ ____ ____  
| | | |  / \  / ___|| |/ / ____|  _ \/ ___| 
| |_| | / _ \| |    | ' /|  _| | |_) \___ \ 
|  _  |/ ___ \ |___ | . \| |___|  _ < ___) |
|_| |_/_/   \_\____|_|\_\_____|_| \_\____/ 
                                           
 _   _ _____ _     _         ____ ____ _____ 
| | | | ____| |   | |       / ___|  _ \_   _|
| |_| |  _| | |   | |      | |  _| |_) || |  
|  _  | |___| |___| |___   | |_| |  __/ | |  
|_| |_|_____|_____|_____|___\____|_|    |_|  
                       |_____|    InternShield           
EOF

    # HACKERS AI Sub-Banner in Purple
    echo -e "\n${PURPLE}${BOLD}   [ H A C K E R S   A I   C O N F I G   T O O L ]${NC}"
    echo -e "${BLUE}   ===============================================${NC}\n"

    sleep 1
    echo -e "${GREEN}[*] Authenticating user credentials with the mainframe...${NC}"
    sleep 1
    echo -e "${GREEN}[*] Decrypting configuration protocols...${NC}\n"
    sleep 1
}

# --- 2. Prompt for Activation Key ---
prompt_for_key() {
    echo -e "${CYAN}>>>${NC} Please enter your AI Activation Key (API Key): "
    read -r -s ACTIVATION_KEY
    if [[ -z "$ACTIVATION_KEY" ]]; then
        echo -e "\n${RED}[!] Error: Activation Key cannot be empty. Connection aborted.${NC}" >&2
        exit 1
    fi
    echo -e "${GREEN}[*] Key securely acquired in volatile memory.${NC}\n"
}

# --- 3. Build Configuration File ---
configure_sgpt() {
    echo -e "${YELLOW}[*] Synthesizing ShellGPT configuration matrix...${NC}"
    
    mkdir -p "$CONFIG_DIR" || { 
        echo -e "${RED}[!] Error: Failed to create config directory.${NC}" >&2; return 1; 
    }

    # Writing to .sgptrc
    cat > "$CONFIG_FILE" << EOF
# Auto-generated by HACKERS_SHELL_GPT Setup Script
DEFAULT_MODEL=$DEFAULT_MODEL
USE_LITELLM=$USE_LITELLM
OPENAI_API_KEY=$ACTIVATION_KEY
EOF
    echo -e "${GREEN}[+] Configuration successfully written to $CONFIG_FILE${NC}\n"
}

# --- 4. Inject Environment Variables ---
export_env_variables() {
    echo -e "${YELLOW}[*] Calibrating system environment variables...${NC}"
    
    # Export for current session
    export AZURE_API_BASE="$API_BASE_URL"
    export AZURE_API_VERSION="$AZURE_API_VERSION"
    export OPENAI_API_KEY="$ACTIVATION_KEY"

    # Inject into .bashrc or .zshrc for persistence
    if ! grep -q "AZURE_API_BASE" "$SHELL_RC_FILE"; then
        echo "" >> "$SHELL_RC_FILE"
        echo "# --- HACKERS_SHELL_GPT AI Config ---" >> "$SHELL_RC_FILE"
        echo "export AZURE_API_BASE=\"$API_BASE_URL\"" >> "$SHELL_RC_FILE"
        echo "export AZURE_API_VERSION=\"$AZURE_API_VERSION\"" >> "$SHELL_RC_FILE"
        echo "export OPENAI_API_KEY=\"$ACTIVATION_KEY\"" >> "$SHELL_RC_FILE"
        echo -e "${GREEN}[+] Variables injected into $SHELL_RC_FILE for persistent uplink.${NC}"
    else
        echo -e "${CYAN}[i] Environment variables already exist in $SHELL_RC_FILE.${NC}"
    fi
    echo ""
}

# --- 5. Verify Setup ---
verify_env_variables() {
    echo -e "${YELLOW}[*] Running diagnostic checks on variables...${NC}"
    echo -e "    ${CYAN}AZURE_API_BASE:${NC} ${AZURE_API_BASE:-"Not set"}"
    echo -e "    ${CYAN}AZURE_API_VERSION:${NC} ${AZURE_API_VERSION:-"Not set"}"
    echo -e "    ${CYAN}DEFAULT_MODEL:${NC} $DEFAULT_MODEL"
    echo ""
}

# --- 6. Execution & Testing ---
execute_sgpt() {
    if ! command -v sgpt >/dev/null 2>&1; then
        echo -e "${RED}[!] Error: 'sgpt' command not found.${NC}" >&2
        echo -e "${YELLOW}[i] Tip: Ensure you have installed it via 'pip install shell-gpt[litellm]'${NC}"
        return 1
    fi

    echo -e "${GREEN}[*] Neural link established. Sending test packet to AI...${NC}\n"
    
    # Run a quick test prompt to ensure it works
    sgpt "Output only the words 'HACKERS AI CONNECTION SUCCESSFUL.' in green text using bash ANSI codes."
}

# --- Main Execution Block ---
main() {
    print_banner
    prompt_for_key
    configure_sgpt
    export_env_variables
    verify_env_variables
    execute_sgpt
    
    echo -e "\n${CYAN}${BOLD}>>> Setup Complete. You may now use 'sgpt <prompt>' in your terminal! <<<${NC}"
}

main
